name: Vconnect
description: A new Flutter project.
publish_to: 'none'  # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  faker: ^2.1.0
  file_picker: ^5.3.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  google_sign_in: ^5.3.1
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.1
  flutter_chat_ui: ^1.6.8
  flutter_firebase_chat_core: ^1.0.0  # Assuming a version number. Update as required.
  flutter_signin_button: ^2.0.0
  http: ^0.13.6
  image_picker: ^0.8.7+5
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  change_app_package_name: ^1.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700

  # Enable the asset directory for SVG files
  assets:
    - assets/