// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkbzPMtcjWQRSB5Dlad__ErWlcqNZzqog',
    appId: '1:936922336672:web:2462389bc2a1ac5f32e8c5',
    messagingSenderId: '936922336672',
    projectId: 'chat-app-final-45a00',
    authDomain: 'chat-app-final-45a00.firebaseapp.com',
    storageBucket: 'chat-app-final-45a00.appspot.com',
    measurementId: 'G-V979N7N84C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4BDyHIuCPJHNdCU6wErAcZkOxERFCsU8',
    appId: '1:936922336672:android:12031742853d526732e8c5',
    messagingSenderId: '936922336672',
    projectId: 'chat-app-final-45a00',
    storageBucket: 'chat-app-final-45a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArK2rhkZyKrlCU5P5hLqjg-Sb-yq6F2FE',
    appId: '1:936922336672:ios:4ee70c8ebed0b8ba32e8c5',
    messagingSenderId: '936922336672',
    projectId: 'chat-app-final-45a00',
    storageBucket: 'chat-app-final-45a00.appspot.com',
    androidClientId: '936922336672-075sejbmqv8cun1h8t06d42n0amrm0lr.apps.googleusercontent.com',
    iosClientId: '936922336672-6sjgsbi59taivmjogkhrqn1n5p5q2dts.apps.googleusercontent.com',
    iosBundleId: 'com.qoder.vconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArK2rhkZyKrlCU5P5hLqjg-Sb-yq6F2FE',
    appId: '1:936922336672:ios:4ee70c8ebed0b8ba32e8c5',
    messagingSenderId: '936922336672',
    projectId: 'chat-app-final-45a00',
    storageBucket: 'chat-app-final-45a00.appspot.com',
    androidClientId: '936922336672-075sejbmqv8cun1h8t06d42n0amrm0lr.apps.googleusercontent.com',
    iosClientId: '936922336672-6sjgsbi59taivmjogkhrqn1n5p5q2dts.apps.googleusercontent.com',
    iosBundleId: 'com.qoder.vconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkbzPMtcjWQRSB5Dlad__ErWlcqNZzqog',
    appId: '1:936922336672:web:b433940becc44b6632e8c5',
    messagingSenderId: '936922336672',
    projectId: 'chat-app-final-45a00',
    authDomain: 'chat-app-final-45a00.firebaseapp.com',
    storageBucket: 'chat-app-final-45a00.appspot.com',
    measurementId: 'G-3349FL534Z',
  );

}